config/routes.rb
Rails.application.routes.draw do

  devise_for :users

  root to: "static_pages#index"

  resources :static_pages, only: :show
end

app/models/image.rb
class Image < ActiveRecord::Base
end

app/models/link.rb
class Link < ActiveRecord::Base
end

app/models/to_do.rb
class ToDo < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable,
         :omniauthable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def index
    redirect_to static_page_url(current_user.id) if user_signed_in?
  end

  def show
  end
end

app/helpers/application_helper.rb
module ApplicationHelper

  def resource_name
    :user
  end

 def resource
   @resource ||= User.new
 end

 def devise_mapping
   @devise_mapping ||= Devise.mappings[:user]
 end

end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Inspire</title>
  <%= stylesheet_link_tag    'application', media: 'all' %>
  <%= javascript_include_tag 'application'%>
  <%= csrf_meta_tags %>
</head>
<body>
  <p class="notice"><%= notice %></p>
  <p class="alert"><%= alert %></p>
  <%= yield %>

</body>
</html>

app/views/static_pages/_signup.html.erb
<%= form_for(resource, as: resource_name, url: registration_path(resource_name)) do |f| %>
  <%= devise_error_messages! %>

  <div class="field">
    <%= f.label :email %><br />
    <%= f.email_field :email, autofocus: true %>
  </div>

  <div class="field">
    <%= f.label :password %>
    <% if @minimum_password_length %>
    <em>(<%= @minimum_password_length %> characters minimum)</em>
    <% end %><br />
    <%= f.password_field :password, autocomplete: "off" %>
  </div>

  <div class="field">
    <%= f.label :password_confirmation %><br />
    <%= f.password_field :password_confirmation, autocomplete: "off" %>
  </div>

  <div class="actions">
    <%= f.submit "Sign up" %>
  </div>
<% end %>

<%= render "devise/shared/links" %>
<p><%= button_to "Sign Out", destroy_session_path(resource_name), method: :delete %></p>

app/views/static_pages/show.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title></title>
  </head>
  <body>
    <div class="background-image fadein"></div>
    <ul id="background">
      <li class="fadein"></li>
    </ul>
    <div class="widgets">
      <div id="top-left">Test</div>
      <div id="top-right"> <%= react_component('WeatherWidget') %> </div>
      <div id="center-top"></div>
      <div id="center-middle"> <%= react_component('ClockWidget') %> </div>
      <div id="center-bottom"> <%= react_component('JokesWidget') %> </div>
      <div id="bottom-left"></div>
      <div id="bottom-right"></div>
    </div>
  </body>
</html>